### ISSUE TITLE
GTNH 2.6.1 服务器放置后导致被踢出

### ISSUE THREAD

**Issue by MikuMiddo** [ElytraServers/Overpowered#3]
重新进入后放置的 上维领域超因果单元 会变成.name方块 同时后台报错踢出玩家 但不会导致崩溃

以下为报错

```
[15:53:55] [Server thread/ERROR] [FML]: A TileEntity BaseMetaTileEntity(gregtech.api.metatileentity.BaseMetaTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: mTextures must not be null
        at RFB-Launch//cn.taskeren.op.gt.single.OP_DebugEnergyHatch.newMetaEntity(OP_DebugEnergyHatch.kt:52) ~[OP_DebugEnergyHatch.class:?]
        at RFB-Launch//cn.taskeren.op.gt.single.OP_DebugEnergyHatch.newMetaEntity(OP_DebugEnergyHatch.kt:28) ~[OP_DebugEnergyHatch.class:?]
        at RFB-Launch//gregtech.api.metatileentity.CommonMetaTileEntity.createNewMetatileEntity(CommonMetaTileEntity.java:41) ~[CommonMetaTileEntity.class:?]
        at RFB-Launch//gregtech.api.metatileentity.CommonMetaTileEntity.loadMetaTileNBT(CommonMetaTileEntity.java:81) ~[CommonMetaTileEntity.class:?]
        at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.setInitialValuesAsNBT(BaseMetaTileEntity.java:210) ~[BaseMetaTileEntity.class:?]
        at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145839_a(BaseMetaTileEntity.java:170) ~[BaseMetaTileEntity.class:?]
        at RFB-Launch//net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
        at RFB-Launch//net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
        at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
        at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
        at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
        at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
        at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
        at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
        at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
        at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
        at RFB-Launch//net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
        at RFB-Launch//net.minecraft.world.World.func_72838_d(World.java:1336) [ahb.class:?]
        at RFB-Launch//net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:301) [oi.class:?]
        at RFB-Launch//net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:161) [oi.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) [NetworkDispatcher.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:?]
        at RFB-Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by Taskeren** [comment]
请提供模组版本

**Comment by MikuMiddo** [comment]
> 请提供模组版本
Overpowered-v1.0.2 github上下的最新的release
[Overpowered-v1.0.2.jar](https://github.com/ElytraServers/Overpowered/releases/download/v1.0.2/Overpowered-v1.0.2.jar)
